In [102]:
import numpy as np

class Bandit:
    actions = []
    rewards = []
    estimated_reward = []
    total_steps = 0
    step = 0
    
    def initialization(self):
        self.actions = ['left', 'right', 'up', 'down']
        self.rewards = np.random.randint(1, size=4)
        self.estimated_rewards = np.random.randint(1, size=4)
        self.total_steps = 100
        self.selection = np.random.randint(1, size=4)
    
    def working(self):
        
        for i in range(self.total_steps):
            self.rewards = np.random.randint(50, size=4)
            if i % 10 != 0:
                val = max(self.estimated_rewards)
                index = self.estimated_rewards.tolist().index(val)
                Action = self.actions[index]
            else:
                rand = (np.random.randint(4, size=1))
                Action = self.actions[rand[0]]
            
            Reward = self.rewards[self.actions.index(Action)]
            print(self.rewards)
            print(self.estimated_rewards)
            self.selection[self.actions.index(Action)] = self.selection[self.actions.index(Action)] + 1
            
            alpha = 1 / self.selection[self.actions.index(Action)]
            self.estimated_rewards[self.actions.index(Action)] = self.estimated_rewards[self.actions.index(Action)] + alpha * (Reward - self.estimated_rewards[self.actions.index(Action)])
        print(self.selection)
        return self.estimated_rewards

In [103]:
b = Bandit()
b.initialization()
arr = b.working()
arr

[21 17  3  2]
[0 0 0 0]
[22 38 15 37]
[ 0 17  0  0]
[46 29 32 47]
[ 0 27  0  0]
[47 28  5 39]
[ 0 27  0  0]
[13 24 17 49]
[ 0 27  0  0]
[21 26 44 16]
[ 0 26  0  0]
[13 19 47 28]
[ 0 26  0  0]
[11 15 15 18]
[ 0 25  0  0]
[29 13 16 41]
[ 0 23  0  0]
[48 24  1 34]
[ 0 21  0  0]
[42 19 16 22]
[ 0 21  0  0]
[23 46 29  7]
[ 0 21 16  0]
[38 49 27 39]
[ 0 23 16  0]
[ 3 28  2 16]
[ 0 25 16  0]
[47  0 25 30]
[ 0 25 16  0]
[ 5 25 32 33]
[ 0 23 16  0]
[29 17 15 47]
[ 0 23 16  0]
[38 43 16 22]
[ 0 22 16  0]
[11  9 28 27]
[ 0 23 16  0]
[ 2 42 25 33]
[ 0 22 16  0]
[45 23  6 49]
[ 0 23 16  0]
[21  1  3 18]
[ 0 23 16  0]
[33  7 48 15]
[ 0 21 16  0]
[25 36 41 21]
[ 0 20 16  0]
[ 4 33 32 14]
[ 0 20 16  0]
[44 12 23 47]
[ 0 20 16  0]
[15 17 36 15]
[ 0 19 16  0]
[33 38 19 49]
[ 0 18 16  0]
[13 35 40 38]
[ 0 18 16  0]
[28 18 18  3]
[ 0 18 16  0]
[19 21 49 43]
[ 0 18 16  0]
[ 8 29 44 49]
[ 0 18 32  0]
[29 40 40 30]
[ 0 18 36  0]
[32 19 47 19]
[ 0 18 37  0]
[10 24 23  2]
[ 0 18 39  0]
[45 41 30 20]
[ 0 18 36 

array([ 0, 11, 12, 10])

In [65]:
result = arr.tolist().index(2)
result

3

In [26]:
l = [2, 3, 5, 6]
a = max(l)

In [28]:
l.index(5)

2